##########################################################
# application.yaml   (used for development purposes)
#
# NOTE:  Make sure there are no leading spaces on any of these lines
##########################################################
name: app1
server.servlet.context-path: /app1
server.port: 8080

# Set the Active profile to be dev
spring.profiles.active: dev

# Disable cors check because we are running in local dev mode
# NOTE:  order is important.  Make sure disable.cors comes *AFTER* you set the profile
disable.cors: true

# Tell Spring to disable DataSource Auto Configuration (so you can run a springboot app without a datasource
spring.autoconfigure:
  exclude:
  - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
    - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration


# Tell Spring to not run flyway automatically
# NOTE:  In the DataSourceConfig, java code is used to run a flyway migrate
spring.flyway.enabled: false

##########################################################
# Database Settings
##########################################################
app.datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/app1_db
    username: app1_user
    password: secret
    schema: app1_db
    maxPoolSize: 10
