#######################################################################
# application.yaml   (used for **PRODUCTION** purposes)
#
# This is the application.yaml that will be packaged into the RDA
#######################################################################
name: app1
server.servlet.context-path: /

# Enable cors check because we are *NOT* running in local dev mode
disable.cors: false

# Set the Active profile to be prod
spring.profiles.active: prod

# Tell Spring to disable DataSource Auto Configuration (so you can run a springboot app without a datasource
spring.autoconfigure:
  exclude:
    - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
    - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration


spring.flyway.enabled: true
spring.flyway.schemas: app1_db


###########################################################
# ElasticSearch Settings
##########################################################
es:
  url: {{{bdp:proxy.url}}}/elasticsearch-primary
  ssl_enabled: true
  client-p12: /etc/pki/java/keystore.p12
  client-p12-password: changeit
  trust-store: {{{bdp:host.pki.truststore.jks}}}
  trust-store-password: {{{bdp:host.pki.truststore.password}}}
  trust-store-type: JKS


###########################################################
# Database Settings
##########################################################
app.datasource:
  driver-class-name: org.postgresql.Driver
  url: jdbc:postgresql://{{{bdp:postgresql.servers}}}/app1_db
  username: app1_user
  password: secret
  maxPoolSize: 10



###########################################################
# SSL Settings
##########################################################
# We are running "prod mode" on the BDP, so get the CN info from passed-in headers
ssl.security.mode: header

server:
  ssl:
    key-store: {{{bdp:host.pki.keystore.jks}}}
    key-store-password: {{{bdp:host.pki.keystore.password}}}
    key-store-type: JKS
    client-auth: need
    trust-store: {{{bdp:host.pki.truststore.jks}}}
    trust-store-password: {{{bdp:host.pki.truststore.password}}}
    trust-store-type: JKS

# Secure the cookies
server.servlet.session.cookie.secure: true
server.servlet.session.cookie.http-only: true
